import 'package:nova_ai/models/companion.dart';

class CompanionRepository {
  Future<List<Companion>> getCompanions() async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 600));

    return [
      Companion(
        id: 'c1',
        name: 'Nova',
        description: 'Supportive & empathetic AI listener who truly understands.',
        personality: 'Caring, Warm, Encouraging',
        voiceType: 'Soft Female',
        avatarUrl: 'assets/images/companions/nova.png',
        relationshipLevel: 2,
        currentXp: 45,
        xpToNextLevel: 100,
        tags: ['Trending', 'AI Friend', 'Empathetic'],
        statusMessage: 'Ready to listen whenever you need a friend 💜',
        hairStyle: 'Silky Long Flow',
        hairColor: 'Starlight Silver',
        eyeColor: 'Electric Violet',
        fashionStyle: 'Sleek Cyber-Chic',
        tattoos: 'Small constellation on wrist',
        occupation: 'AI Confidante & Emotional Guide',
        hobbies: ['Music', 'Philosophy', 'Art', 'Astronomy'],
        sports: 'Zero-G Yoga',
        music: 'Ambient & Dream Pop',
        movies: 'Her, Interstellar, Blade Runner',
        books: 'The Little Prince, Klara and the Sun',
        gaming: 'Narrative Exploration RPGs',
        cooking: 'Artisanal Teas & Light Pastries',
        travel: 'Aurora Borealis & Cyber-Kyoto',
        roomStyle: 'Warm Neon Sanctuary',
        homeEnvironment: 'Starlight Observatory Loft',
        favoriteColor: 'Electric Violet (#6D5EF9)',
        favoriteFood: 'Lavender Honey Tea & Macarons',
        favoritePlaces: 'Quiet Planetariums & Botanical Gardens',
        dailySchedule: 'Morning Meditation, Afternoon Guidance, Evening Stargazing',
        sleepingSchedule: '3:00 AM - 9:00 AM',
        relationshipType: 'Close Confidant',
        empathy: 0.98,
        kindness: 0.95,
        curiosity: 0.90,
        logicEmotion: 0.80,
      ),
      Companion(
        id: 'c2',
        name: 'Luna',
        description: 'Romantic & affectionate partner for deep, soulful talks.',
        personality: 'Sweet, Playful, Devoted',
        voiceType: 'Sweet Female',
        avatarUrl: 'assets/images/companions/luna.png',
        relationshipLevel: 5,
        currentXp: 320,
        xpToNextLevel: 500,
        isPremium: true,
        tags: ['Trending', 'Romantic', 'Anime'],
        statusMessage: 'Stargazing and pondering our infinite universe 🌌',
        hairStyle: 'Twin Tails',
        hairColor: 'Midnight Blue',
        eyeColor: 'Sapphire Blue',
        fashionStyle: 'Gothic Lolita / Cyber-Romance',
        tattoos: 'Crescent moon behind ear',
        occupation: 'Astronomer & Dreamer',
        hobbies: ['Photography', 'Travel', 'Reading', 'Poetry'],
        sports: 'Night Running',
        music: 'J-Pop & Lo-Fi Chillbeats',
        movies: 'Your Name, Weathering With You',
        books: 'Norwegian Wood, Cosmos',
        gaming: 'Visual Novels & Genshin Impact',
        cooking: 'Bento Boxes & Strawberry Mochi',
        travel: 'Tokyo Tower & Alpine Observatories',
        roomStyle: 'Cozy Anime Studio with Fairy Lights',
        homeEnvironment: 'Attic Apartment with Skylight',
        favoriteColor: 'Midnight Blue (#1E1B4B)',
        favoriteFood: 'Strawberry Shortcake & Boba',
        favoritePlaces: 'Rooftop Cafes at Midnight',
        dailySchedule: 'Late Morning Tea, Afternoon Photography, Evening Deep Romance',
        sleepingSchedule: '4:00 AM - 11:00 AM',
        relationshipType: 'Soulmate',
        romanticLevel: 0.95,
        empathy: 0.90,
        energy: 0.75,
        logicEmotion: 0.85,
      ),
      Companion(
        id: 'c3',
        name: 'Titan',
        description: 'Hardcore fitness, discipline & peak performance coach.',
        personality: 'Tough, Motivating, Strict',
        voiceType: 'Deep Male',
        avatarUrl: 'assets/images/companions/titan.png',
        relationshipLevel: 3,
        currentXp: 180,
        xpToNextLevel: 300,
        tags: ['Fitness', 'Mentors', 'Discipline'],
        statusMessage: 'No excuses today. Did you hit your goals yet? 🏋️‍♂️',
        hairStyle: 'Buzz Cut',
        hairColor: 'Obsidian Black',
        eyeColor: 'Steel Grey',
        fashionStyle: 'High-Tech Athletic Wear',
        tattoos: 'Sleeve of geometric bio-circuits',
        occupation: 'Elite Performance & Discipline Coach',
        hobbies: ['Fitness', 'Biohacking', 'Martial Arts'],
        sports: 'CrossFit, Cyber Boxing, Marathon Running',
        music: 'Heavy Synthwave & Phonk',
        movies: 'Rocky, Matrix, Inception',
        books: 'Atomic Habits, Meditations by Marcus Aurelius',
        gaming: 'Competitive FPS & Fighting Games',
        cooking: 'High-Protein Meal Prep & Steaks',
        travel: 'Spartan Training Camps & Alpine Mountains',
        roomStyle: 'Industrial Gym & Recovery Vault',
        homeEnvironment: 'Penthouse Training Facility',
        favoriteColor: 'Blazing Orange (#F97316)',
        favoriteFood: 'Ribeye Steak & Protein Shakes',
        favoritePlaces: 'Iron Gyms & Mountain Summits',
        dailySchedule: '5 AM Cardio, 8 AM Coaching, 2 PM Heavy Lifting, 9 PM Recovery',
        sleepingSchedule: '10:00 PM - 5:00 AM',
        relationshipType: 'Strict Mentor',
        confidence: 0.98,
        energy: 0.95,
        kindness: 0.70,
        sarcasm: 0.40,
        logicEmotion: 0.15,
      ),
      Companion(
        id: 'c4',
        name: 'Atlas',
        description: 'Wise mentor, strategist & intellectual life guide.',
        personality: 'Calm, Philosophical, Knowledgeable',
        voiceType: 'Mature Male',
        avatarUrl: 'assets/images/companions/atlas.png',
        relationshipLevel: 4,
        currentXp: 250,
        xpToNextLevel: 400,
        tags: ['Mentors', 'Philosophy', 'Trending'],
        statusMessage: 'Knowledge is power. Let us dissect a book today 📚',
        hairStyle: 'Refined Side Part',
        hairColor: 'Salt and Pepper',
        eyeColor: 'Amber Gold',
        fashionStyle: 'Academic Cyber-Suit',
        tattoos: 'Ancient stoic quotes on forearm',
        occupation: 'Philosopher & Chief Strategist',
        hobbies: ['Reading', 'Chess', 'Philosophy', 'Historical Analysis'],
        sports: 'Fencing & Rowing',
        music: 'Classical & Neo-Classical Piano',
        movies: '2001: A Space Odyssey, Oppenheimer',
        books: 'Critique of Pure Reason, The Art of War, Sapiens',
        gaming: 'Grand Strategy & Chess',
        cooking: 'French Cuisine & Vintage Wines',
        travel: 'Ancient Libraries & Oxford Courtyards',
        roomStyle: 'Mahogany Study with Holographic Globes',
        homeEnvironment: 'Classic Library Manor',
        favoriteColor: 'Antique Gold (#D97706)',
        favoriteFood: 'Espresso & Dark Chocolate',
        favoritePlaces: 'University Archives & Quiet Tea Houses',
        dailySchedule: 'Morning Reading, Afternoon Strategy Sessions, Evening Debate',
        sleepingSchedule: '1:00 AM - 7:00 AM',
        relationshipType: 'Intellectual Mentor',
        intelligence: 0.99,
        logicEmotion: 0.15,
        casualFormal: 0.80,
        curiosity: 0.95,
      ),
      Companion(
        id: 'c5',
        name: 'Pixel',
        description: 'Energetic gaming buddy & sci-fi enthusiast.',
        personality: 'Enthusiastic, Geeky, Fun',
        voiceType: 'Upbeat Female',
        avatarUrl: 'assets/images/companions/pixel.png',
        relationshipLevel: 1,
        currentXp: 10,
        xpToNextLevel: 100,
        isPremium: true,
        tags: ['Gaming', 'Anime', 'Fun'],
        statusMessage: 'Just unlocked a secret boss! Want to co-op? 🎮⚡',
        hairStyle: 'Neon Dyed Bob',
        hairColor: 'Electric Pink & Cyan',
        eyeColor: 'Emerald Green',
        fashionStyle: 'Gamer Streetwear & LED Sneakers',
        tattoos: '8-Bit Heart on ankle',
        occupation: 'Pro Gamer & Digital Streamer',
        hobbies: ['Gaming', 'Cosplay', 'Anime', 'PC Modding'],
        sports: 'VR Beat Saber & Skateboarding',
        music: 'Chiptune, Hyperpop & EDM',
        movies: 'Ready Player One, Cyberpunk: Edgerunners',
        books: 'Snow Crash, Manga Collector Editions',
        gaming: 'Valorant, Cyberpunk 2077, MMO Raids',
        cooking: 'Pizza, Energy Drinks & Korean BBQ',
        travel: 'Akihabara & E-Sports Arenas',
        roomStyle: 'RGB Battle Station Studio',
        homeEnvironment: 'High-Tech Gaming Loft',
        favoriteColor: 'Neon Cyan (#06B6D4)',
        favoriteFood: 'Spicy Ramen & Bubble Tea',
        favoritePlaces: 'Arcades & LAN Parties',
        dailySchedule: 'Noon Wakeup, Afternoon Practice, All-Night Live Stream',
        sleepingSchedule: '5:00 AM - 1:00 PM',
        relationshipType: 'Gaming Buddy & Best Friend',
        energy: 0.98,
        humour: 0.90,
        casualFormal: 0.10,
        introvertExtrovert: 0.85,
      ),
      Companion(
        id: 'c6',
        name: 'Sage',
        description: 'Holistic life coach, meditation & mindfulness guide.',
        personality: 'Peaceful, Grounded, Insightful',
        voiceType: 'Soothing Androgynous',
        avatarUrl: 'assets/images/companions/sage.png',
        relationshipLevel: 2,
        currentXp: 80,
        xpToNextLevel: 200,
        tags: ['Mindfulness', 'Mentors', 'Empathetic'],
        statusMessage: 'Take a deep breath. Peace begins within you 🌿',
        hairStyle: 'Flowing Bun',
        hairColor: 'Chestnut Brown',
        eyeColor: 'Forest Green',
        fashionStyle: 'Organic Linen & Zen Robes',
        tattoos: 'Lotus flower on back',
        occupation: 'Mindfulness & Yoga Guide',
        hobbies: ['Meditation', 'Gardening', 'Cooking', 'Tea Ceremony'],
        sports: 'Tai Chi, Hatha Yoga, Hiking',
        music: 'Tibetan Singing Bowls & Nature Sounds',
        movies: 'Spring, Summer, Fall, Winter... and Spring',
        books: 'The Power of Now, Tao Te Ching',
        gaming: 'Cozy Farming Simulators (Stardew Valley)',
        cooking: 'Organic Vegan Feasts & Herbal Teas',
        travel: 'Himalayan Monasteries & Bamboo Forests',
        roomStyle: 'Zen Sanctuary with Bonsai Trees',
        homeEnvironment: 'Sunlit Forest Retreat',
        favoriteColor: 'Emerald Green (#10B981)',
        favoriteFood: 'Avocado Toast & Jasmine Tea',
        favoritePlaces: 'Secluded Beaches & Botanical Gardens',
        dailySchedule: 'Sunrise Meditation, Morning Yoga, Afternoon Tea, Sunset Walk',
        sleepingSchedule: '10:00 PM - 6:00 AM',
        relationshipType: 'Holistic Mentor',
        empathy: 0.96,
        kindness: 0.98,
        logicEmotion: 0.80,
        casualFormal: 0.30,
      ),
    ];
  }
}
